### ISSUE TITLE
If all products within a category are sold out, nothing is displayed

### ISSUE THREAD

**Issue by ChristopherDosin** [Shape-and-Shift/SasProductSoldOutToEnd#2]
We need to think about to re-factor the plugin.

**Comment by vienthuong** [comment]
I fixed it in the latest commit. Would you mind to double check it?

**Comment by ChristopherDosin** [comment]
Fixed in https://github.com/Shape-and-Shift/shopware-product-sold-out-to-end/commit/4c7333d39e09742eb88422b6e4ae77a8e5503116
